### PR TITLE
Update to latest nuget for dependencies

### PR DESCRIPTION
**Pull request by rohitvipin**
Please take a moment to fill out the following:

Fixes # .https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/251

Changes Proposed in this pull request:
- Nuget dependency updates

### CODE REVIEW

**Comment by prom3theu5** [comment]
Any idea when this is going to be merged in??
This is the only library I have now that requires older dependencies. Worried that the December cutoff for old api usage is going to effect 3 of my apps.

**Comment by moreirawebmaster** [comment]
Any idea when this is going to be merged in??

**Comment by rohitvipin** [comment]
I am still waiting on the library maintainers, they haven't looked into this for so long. I might soon have my own fork released as nuget

**Comment by mimunoz** [comment]
I asked today in #270

**Comment by rdelrosario** [comment]
Thanks for your contribution @rohitvipin

**Comment by moreirawebmaster** [comment]
@rdelrosario when update nuget?

**Pull request merged**
